name: 'Unity Test Publisher'
author: 'Vladimir Kryukov'
description: 'Analyze Unity Test Report and publish results'
branding:
  icon: 'check-circle'
  color: 'red'
inputs:
  githubToken:
    description: 'GITHUB_TOKEN'
    required: true
  editModeReport:
    description: 'unity edit mode test report xml file to analyze'
    required: false
  playModeReport:
    description: 'unity play mode test report xml file to analyze'
    required: false
  workdirPrefix:
    description: 'prefix on build machine to ignore in report'
    required: false
    default: '/github/workspace/'
  failOnTestFailures:
    description: 'fail run if there were test failures'
    required: false
    default: 'false'
  failIfNoTests:
    description: 'fail run if there were no test results found'
    required: false
    default: 'true'
outputs:
  time:
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
