name: 'Unity Tests'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  
jobs:
  # unit tests
  units:
    name: 'Unit Tests for Action'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
      
  # run unity tests & analyze result
  test:
    name: 'Analyze Test Results'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: 'Publish test results'
        if: ${{ always() }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          editModeReport: ./reports/editmode-results.xml
          playModeReport: ./reports/playmode-results.xml
